onEvent('fluid.registry', event => {
    event.create('valine_s1ex:liquefied_compressed_air')
    .thickTexture(0xF5F5F5)
    .bucketColor(0xF5F5F5)
    .displayName('Liquefied Compressed Air')
    event.create('valine_s1ex:propylene')
    .thickTexture(0xa9a9a9)
    .bucketColor(0xa9a9a9)
    .displayName('Propylene')
    event.create('valine_s1ex:polypropylene')
    .thickTexture(0xa9a9a9)
    .bucketColor(0xa9a9a9)
    .displayName('Polypropylene')
    event.create('valine_s1ex:heptane')
    .thickTexture(0xffdab9)
    .bucketColor(0xffdab9)
    .displayName('Heptane')
    event.create('valine_s1ex:toluene')
    .thickTexture(0x8b4513)
    .bucketColor(0x8b4513)
    .displayName('Toluene')
    event.create('valine_s1ex:vinyl_chloride')
    .thickTexture(0xebf6f7)
    .bucketColor(0xebf6f7)
    .displayName('Vinyl Chloride')
    event.create('valine_s1ex:fermented_biodiesel')
    .thickTexture(0xcc7be1)
    .bucketColor(0xcc7be1)
    .displayName('Fermented Biodiesel')
    event.create('valine_s1ex:unknown_darkmatter')
    .thickTexture(0x333631)
    .bucketColor(0x333631)
    .displayName('Unknown Darkmatter')
    event.create('valine_s1ex:molten_midnight')
    .thickTexture(0x1f3134)
    .bucketColor(0x1f3134)
    .displayName('molten midnight')
    event.create('valine_s1ex:molten_tungsten_carbite')
    .thickTexture(0x203744)
    .bucketColor(0x203744)
    .displayName('molten tungsten carbite')
    event.create('valine_s1ex:molten_infinity')
    .thickTexture(0xc4a3bf)
    .bucketColor(0xc4a3bf)
    .displayName('molten Infinity');
})