onEvent('item.registry', event => {
	event.create('valine_s1ex:andesite_with_iron').displayName('andesite mixture').tooltip("もっと混ぜろ")
	event.create('valine_s1ex:eliminated_core').tooltip("全部いなくなれ")
	event.create('valine_s1ex:stabilized_core').tooltip("安定しろ")
	event.create('valine_s1ex:redstone_transmission_coil').tooltip("とらんすみっしょん！")
	event.create('valine_s1ex:redstone_conductance_coil').tooltip("コンダクタンスって何？")
	event.create('valine_s1ex:inactive_redstone_servo').tooltip("起動待機中")
	event.create('valine_s1ex:inactive_redstone_flux_coil').tooltip("起動待機中")
	event.create('valine_s1ex:inactive_redstone_transmission_coil').tooltip("起動待機中")
	event.create('valine_s1ex:inactive_redstone_conductance_coil').tooltip("起動待機中")
	event.create('valine_s1ex:azure_menril_ingot').tooltip("メンリルとは......なんだ？")
	event.create('valine_s1ex:redalloy_ingot').tooltip("誰かこの大ぐらいをどうにかしてくれ")
	event.create('valine_s1ex:mysterious_mixture').tooltip("謎にして邪悪")
	event.create('valine_s1ex:chrome_ingot').tooltip("INTERNET YAMERO")
	event.create('valine_s1ex:pyrotheum_dust').tooltip("CNP:Taurvi")
	event.create('valine_s1ex:cryotheum_dust').tooltip("⑨")
	event.create('valine_s1ex:aerotheum_dust').tooltip("wind climbing")
	event.create('valine_s1ex:petrotheum_dust').tooltip("グルメスパイザー")
	event.create('valine_s1ex:handmade_circuit').tooltip("お手製は凝るもの")
	event.create('valine_s1ex:high_node_item_circuit').tooltip("アイテムといいつつそれ以外にも使う")
	event.create('valine_s1ex:high_node_fluid_circuit').tooltip("Advanced Rocketryかなんかのパクリ")
	event.create('valine_s1ex:highend_circuit').tooltip("乱用注意")
	event.create('valine_s1ex:basic_circuit_base').tooltip("ベーシック以外そんざいしないのにね")
	event.create('valine_s1ex:empty_crystal').tooltip("からっぽ。そこにはなにもない。だからなんでも詰め込める")
	event.create('valine_s1ex:ether_crystal').tooltip("my guiding star.")
	event.create('valine_s1ex:arc_element_crystal').tooltip("AFK")
	event.create('valine_s1ex:botania_element_crystal').tooltip("botanical technology")
	event.create('valine_s1ex:terrasteel_wire').tooltip("グリーン・リボン")
	event.create('valine_s1ex:resister').tooltip("item.registry")
	event.create('valine_s1ex:osmiridium_ingot').tooltip("いつもの")
	event.create('valine_s1ex:osmiridium_plate').tooltip("これプレートになってる？")
	event.create('valine_s1ex:nichrome_ingot').tooltip("コイルには使わない......なんて言わないが？")
	event.create('valine_s1ex:nichrome_plate').tooltip("pink plate")
	event.create('valine_s1ex:tungstain_carbite_ingot').tooltip("見覚えのある見覚えのない物")
	event.create('valine_s1ex:tungstain_carbite_plate').tooltip("中性子も防げるかな……？")
	event.create('valine_s1ex:mekanism_upgrade_base').tooltip("ベースラインやってる？")
	event.create('valine_s1ex:fractual_mix').tooltip("angel dust")
	event.create('valine_s1ex:sunnarium').tooltip("無限進化からの贈り物")
	event.create('valine_s1ex:enritched_sunnarium').tooltip("放射性ウランは実装したらクラッシュしたので諦めた")
	event.create('valine_s1ex:sunnarium_alloy').tooltip("合金という名のプレート")
	event.create('valine_s1ex:enritched_sunnarium_alloy').tooltip("合金を作るのが面倒とか言わないで")
	event.create('valine_s1ex:nichrome_wire').tooltip("知ってた。")
	event.create('valine_s1ex:nichrome_coil').tooltip("※IEでは使えません")
	event.create('valine_s1ex:high_voltage_module').tooltip("PC用")
	event.create('valine_s1ex:connector').tooltip("Sinytra")
	event.create('valine_s1ex:ash_chip').tooltip("YOU DIED")
	event.create('valine_s1ex:yellow_node').tooltip("とある人物のドリトスに酷似しているらしい")
	event.create('valine_s1ex:valine_hvm').texture('valine_s1ex:item/valine').tooltip("最初はコイル")
	event.create('valine_s1ex:valine_connector').texture('valine_s1ex:item/valine').tooltip("最初はLコネクター")
	event.create('valine_s1ex:valine_de').texture('valine_s1ex:item/valine').tooltip("最初は高圧モジュール")
	event.create('valine_s1ex:valine_tnt').texture('valine_s1ex:item/valine').tooltip("最初はトルエン")
	event.create('valine_s1ex:valine_mys').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_mysins').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_myspur').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_myssup').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_myster').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_mysimp').texture('valine_s1ex:item/valine').tooltip("1000!?")
	event.create('valine_s1ex:valine_dex').texture('valine_s1ex:item/valine').tooltip("最初はenergy card")
	event.create('valine_s1ex:souls_of_different_orders_of_magnitude').texture('valine_s1ex:item/heart').tooltip("So DOOM")
	event.create('valine_s1ex:valine_decore').texture('valine_s1ex:item/valine').tooltip("最初はdraconium core")
	event.create('valine_s1ex:enriched_antimatter_eternal_ingot').tooltip('濃縮反物質化エターナルインゴット')
  	event.create('valine_s1ex:enriched_antimatter_pellet').tooltip('§4俺にッ近寄るなッ！§r')
	event.create('valine_s1ex:eternal_ingot').tooltip("§3§oDon't Fight The Music and revive the melody§r")
	event.create('valine_s1ex:valine').texture("valine_s1ex:item/chem_valine").tooltip('117.15g/mol')
    event.create('valine_s1ex:tuna').tooltip('約125kg')
    event.create('valine_s1ex:compacted_valine3g_pellet').tooltip('圧縮しすぎ')
    event.create('valine_s1ex:valine3g_pellet').tooltip('必須アミノ酸')
	event.create('overdrive:apex_seeker').displayName('§0Apex Seeker§r').texture('valine_s1ex:item/apex_seeker').tooltip("§0and in that light, I find deliverance.§r")
	event.create('overdrive:unparalleled_achievement_l').displayName('比類なき戦果”青の証”').tooltip("技術を司りし§1青§rの星。大海原の様にすべてを飲み込む。")
	event.create('overdrive:unparalleled_achievement_y').displayName('比類なき戦果”白の証”').tooltip("破滅の炎を司りし§f白§rの星。その道はすべて灰燼に帰した。")
	event.create('overdrive:unparalleled_achievement_h').displayName('比類なき戦果”緑の証”').tooltip("つながりを司る§2緑§rの星。大樹の様に廻りて集いし民を守護する。")
	event.create('overdrive:unparalleled_achievement_v').displayName('比類なき戦果”灰の証”').tooltip("極大を司る§7灰§rの星。すべての星は彼のもとへ集う。")
	event.create('overdrive:seeking_fragment').displayName('導きの断片')           .tooltip("§1§obye-bye§r")
	event.create('overdrive:perfect_maximize').displayName('極星と焦点と修羅の決断').tooltip("§2§o望遠鏡の焦点合わせて§r")
	event.create('overdrive:distant_horizons').displayName('創造の水平線')          .tooltip("§3§o水平線の消点探した§r")
	event.create('overdrive:chaotic_breath')  .displayName('混沌の吐息')            .tooltip("§4§o漏れたため息が苦くても§r")
	event.create('overdrive:mercury_lamp')    .displayName('星明かりのランプ')      .tooltip("§5§o水銀灯の照明落として§r")
	event.create('overdrive:server_eater')    .displayName('サーバーの破壊者')      .tooltip("§6§o「降参なんて冗談じゃない」って§r")
	event.create('overdrive:administrator_authority').displayName('五月光の星花')  .tooltip("§7§oほんの一瞬だけ笑った§r")
	event.create('overdrive:fake_flower').displayName('偽りの星花').texture('overdrive:item/administrator_authority').tooltip("§7§o語りましょう、騙りましょう§r")
})