
#Chemical Atomizer
[atomizer]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 2500
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 1600000

#Chemical Compactor
[compactor]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 2500
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1

#Chemical Combiner
[combiner]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 200 FE
	#Range: > 0
	energyPerTick = 10000
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1

#Chemical Dissolver
[dissolver]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 100 FE
	#Range: > 0
	energyPerTick = 5000
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1

#Chemical Liquifier
[liquifier]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 5000
	#Default: 100 ticks
	#Range: > 1
	ticksPerOperation = 1
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 16000

#Fission
[fission]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 10000000
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 15000
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1

#Fusion
[fusion]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 15000
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 1

