#Maximum health of the common blob
#Range: > 0
commonBlobMaxHealth = 500
#Maximum health of the rare blob
#Range: > 0
rareBlobMaxHealth = 2500
#Maximum health of the legendary blob
#Range: > 0
legendaryBlobMaxHealth = 50000

