/*<recipetype:create:mechanical_crafting>.addRecipe("mechanical_crafter/ender_generator", <item:exponentialpower:ender_generator>,[
    [<item:minecraft:air>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:minecraft:air>],
    [<item:mekanism:sps_casing>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:minecraft:ender_eye>, <item:chemlib:protactinium_ingot>, <item:minecraft:ender_eye>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:mekanism:sps_casing>],
    [<item:mekanism:sps_casing>, <item:botania:gaia_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:solarpanels:photonic_energy_tablet>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:botania:gaia_ingot>, <item:mekanism:sps_casing>],
    [<item:mekanism:sps_casing>, <item:minecraft:ender_eye>, <item:avaritia:neutronium_ingot>, <item:extrautilitiesrebirth:rainbow_generator>, <item:mekaevolution:infinite_control_circuit>, <item:extrautilitiesrebirth:rainbow_generator>, <item:avaritia:neutronium_ingot>, <item:minecraft:ender_eye>, <item:mekanism:sps_casing>],
    [<item:mekanism:sps_port>, <item:mekanism:supercharged_coil>, <item:solarpanels:photonic_energy_tablet>, <item:mekaevolution:infinite_control_circuit>, <item:draconicadditions:chaos_heart>, <item:mekaevolution:infinite_control_circuit>, <item:solarpanels:photonic_energy_tablet>, <item:mekanism:supercharged_coil>, <item:mekanism:sps_port>],
    [<item:mekanism:sps_casing>, <item:minecraft:ender_eye>, <item:avaritia:neutronium_ingot>, <item:extrautilitiesrebirth:rainbow_generator>, <item:mekaevolution:infinite_control_circuit>, <item:extrautilitiesrebirth:rainbow_generator>, <item:avaritia:neutronium_ingot>, <item:minecraft:ender_eye>, <item:mekanism:sps_casing>],
    [<item:mekanism:sps_casing>, <item:botania:gaia_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:solarpanels:photonic_energy_tablet>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:botania:gaia_ingot>, <item:mekanism:sps_casing>],
    [<item:mekanism:sps_casing>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:minecraft:ender_eye>, <item:chemlib:protactinium_ingot>, <item:minecraft:ender_eye>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:mekanism:sps_casing>],
    [<item:minecraft:air>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:mekanism:sps_casing>, <item:minecraft:air>]
    ]);

<recipetype:create:mechanical_crafting>.addRecipe("mechanical_crafter/ender_storage", <item:exponentialpower:ender_storage>,[
    [<item:minecraft:air>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:energy_core_stabilizer>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:minecraft:air>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_provider>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_cell>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:mekanism:ultimate_induction_cell>, <item:industrialforegoing:machine_frame_supreme>, <item:mekaevolution:infinite_control_circuit>, <item:industrialforegoing:machine_frame_supreme>, <item:mekanism:ultimate_induction_cell>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:draconicevolution:energy_core_stabilizer>, <item:draconicevolution:draconium_block>, <item:mekanism:ultimate_induction_provider>, <item:mekaevolution:infinite_control_circuit>, <item:draconicevolution:energy_core>, <item:mekaevolution:infinite_control_circuit>, <item:mekanism:ultimate_induction_provider>, <item:draconicevolution:draconium_block>, <item:draconicevolution:energy_core_stabilizer>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:mekanism:ultimate_induction_cell>, <item:industrialforegoing:machine_frame_supreme>, <item:mekaevolution:infinite_control_circuit>, <item:industrialforegoing:machine_frame_supreme>, <item:mekanism:ultimate_induction_cell>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_provider>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_induction_cell>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:draconium_block>, <item:draconicevolution:awakened_draconium_block>],
    [<item:minecraft:air>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:energy_core_stabilizer>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:draconicevolution:awakened_draconium_block>, <item:minecraft:air>]
    ]);*/